root='/sp/fd/teo/Development/cpmd_WORLD/CPMD/'
arch='OBJ'
version='x'
nproc=8
bin='${root}/${arch}/cpmd.${version}'
testsrc='${root}/../regtests/tests'
ppdir='${root}/../regtests/tests/PP_LIBRARY/'
make='make -j${nproc}'
makedir='${root}/OBJ/'
#cvs_update='cvs update -dP'
nproc_mpi=2
mpi_prefix='mpiexec -n %i'
mpi_suffix='-hostfile /sp/fd/teo/Hosts'
